# Basic
title: 高兴
subtitle: 行万里路，读万卷书.
welcome_message: <a href="http://zhenker.cn/biaobai.html" target="_blank">欢迎到高兴小站来做客！</a>
description: Hi,你好,我是高兴,一名小小的见习魔法师,目前还在魔法学校学习,致力于基础魔法的研究和应用,努力成为一名优秀的魔法师。
creator: <a href="http://www.高兴.cn">@高兴</a>

url: "http://www.高兴.cn"

permalink: /:year/:month/:title/

# Format
rouge: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客
# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
    - {title: 音乐,        in_site: true,  description: 娱乐区,                 url: '/music.html'}
    - {title: DH魔法,       in_site: false,  description: dh's fantastic,   url: '/index-tem.html'}
    - {title: gx记录,     in_site: false,  description: 高兴's GitHub,      url: '/index-gx.html'}
    - {title: 大魔法师,   in_site: true,  description: 大魔法师,                  url: '/friends'}
    - {title: 讨论区,   in_site: true,  description: 讨论区,                  url: '/messageWord.html'}
    - {title: 关于,        in_site: true,  description: 关于作者dh,        url: '/about'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 高兴
    # duoshuo: 
    
# Social
social:
    weibo: dh
    github: dh
  # twitter: 
    gplus: 112373242775367333102
    rss: /feed.xml
    mail: 1612099539@qq.com
  # copyright: http://blog.csdn.net/高兴

# Google Analytics
ga:
    id: UA-86995833-1
    host: www.高兴.cn
